import Fuse from 'fuse.js';

export type Intent = 
  | 'comprar' 
  | 'pagamento' 
  | 'garantia' 
  | 'rastreamento' 
  | 'suporte' 
  | 'saudacao'
  | 'despedida'
  | 'desconhecido';

const INTENT_EXAMPLES = [
  // COMPRAR (40 exemplos)
  { intent: 'comprar', text: 'quero comprar um celular smartphone aparelho' },
  { intent: 'comprar', text: 'quero um iphone apple samsung' },
  { intent: 'comprar', text: 'como faço para adquirir' },
  { intent: 'comprar', text: 'tem no estoque disponibilidade' },
  { intent: 'comprar', text: 'quero trocar de celular' },
  { intent: 'comprar', text: 'vcs vendem celular usado seminovo' },
  { intent: 'comprar', text: 'onde vejo os aparelhos a venda' },
  { intent: 'comprar', text: 'quero pegar um modelo mais novo' },
  { intent: 'comprar', text: 'to atras de um celular bom barato' },
  { intent: 'comprar', text: 'quero ver os precos pra comprar' },
  { intent: 'comprar', text: 'tem vitrine' },
  { intent: 'comprar', text: 'quero dar um celular de presente' },
  { intent: 'comprar', text: 'quero encomendar um iphone' },
  { intent: 'comprar', text: 'tem samsung s23 ultra' },
  { intent: 'comprar', text: 'qual o celular mais vendido' },
  { intent: 'comprar', text: 'estou procurando um celular novo' },
  { intent: 'comprar', text: 'link pra compra' },
  { intent: 'comprar', text: 'quero fechar negocio hoje' },
  { intent: 'comprar', text: 'quais marcas vcs tem' },
  { intent: 'comprar', text: 'quero um celular gamer' },
  { intent: 'comprar', text: 'preciso de um celular urgente' },
  { intent: 'comprar', text: 'me recomenda um smartphone' },
  { intent: 'comprar', text: 'to precisando trocar meu aparelho' },
  { intent: 'comprar', text: 'vou comprar' },
  { intent: 'comprar', text: 'gostaria de fazer um pedido' },
  { intent: 'comprar', text: 'adicionar ao carrinho' },
  { intent: 'comprar', text: 'quero levar um celular' },
  { intent: 'comprar', text: 'quero investir num aparelho top' },
  { intent: 'comprar', text: 'como e o processo de compra' },
  { intent: 'comprar', text: 'vcs entregam se eu comprar' },
  { intent: 'comprar', text: 'onde fica a loja pra comprar' },
  { intent: 'comprar', text: 'fazer pedido' },
  { intent: 'comprar', text: 'como comprar' },
  { intent: 'comprar', text: 'to interessado em um celular' },
  { intent: 'comprar', text: 'botar no carrinho' },
  { intent: 'comprar', text: 'tem xiaomi' },
  { intent: 'comprar', text: 'tem motorola' },
  { intent: 'comprar', text: 'qual e o melhor pra comprar' },
  { intent: 'comprar', text: 'estou querendo adquirir' },
  { intent: 'comprar', text: 'tem desconto se comprar agora' },

  // PAGAMENTO (40 exemplos)
  { intent: 'pagamento', text: 'quais as formas de pagamento' },
  { intent: 'pagamento', text: 'aceita pix cartao de credito' },
  { intent: 'pagamento', text: 'parcela no cartão boleto' },
  { intent: 'pagamento', text: 'qual o preço valor custa' },
  { intent: 'pagamento', text: 'tem juros no parcelamento' },
  { intent: 'pagamento', text: 'faz em quantas vezes' },
  { intent: 'pagamento', text: 'qual o desconto a vista' },
  { intent: 'pagamento', text: 'aceita dois cartoes' },
  { intent: 'pagamento', text: 'o pagamento foi aprovado' },
  { intent: 'pagamento', text: 'como pago' },
  { intent: 'pagamento', text: 'tem desconto no pix' },
  { intent: 'pagamento', text: 'gera boleto' },
  { intent: 'pagamento', text: 'ta caro ta barato' },
  { intent: 'pagamento', text: 'qual e o valor do frete' },
  { intent: 'pagamento', text: 'preciso da nota fiscal nfe' },
  { intent: 'pagamento', text: 'como faco o pagamento' },
  { intent: 'pagamento', text: 'vcs parcelam em 12x' },
  { intent: 'pagamento', text: 'cartao recusou o que fazer' },
  { intent: 'pagamento', text: 'quero cancelar o pagamento' },
  { intent: 'pagamento', text: 'quero estorno do meu dinheiro' },
  { intent: 'pagamento', text: 'onde vejo o preco' },
  { intent: 'pagamento', text: 'quanto fica tudo' },
  { intent: 'pagamento', text: 'passa cartao de debito' },
  { intent: 'pagamento', text: 'aceita mercado pago' },
  { intent: 'pagamento', text: 'aceita picpay' },
  { intent: 'pagamento', text: 'tem taxa de juros' },
  { intent: 'pagamento', text: 'custa quanto' },
  { intent: 'pagamento', text: 'qual e o custo' },
  { intent: 'pagamento', text: 'pagamento pendente' },
  { intent: 'pagamento', text: 'como manda o comprovante' },
  { intent: 'pagamento', text: 'ja paguei' },
  { intent: 'pagamento', text: 'fiz o pix' },
  { intent: 'pagamento', text: 'quero cupom de desconto' },
  { intent: 'pagamento', text: 'qual e a chave pix' },
  { intent: 'pagamento', text: 'pagar na entrega' },
  { intent: 'pagamento', text: 'boleto vence hoje' },
  { intent: 'pagamento', text: 'cartao de credito bloqueou' },
  { intent: 'pagamento', text: 'segunda via do boleto' },
  { intent: 'pagamento', text: 'transferencia bancaria' },
  { intent: 'pagamento', text: 'da pra parcelar' },

  // GARANTIA/DEFEITO (40 exemplos)
  { intent: 'garantia', text: 'meu celular estragou' },
  { intent: 'garantia', text: 'veio com defeito' },
  { intent: 'garantia', text: 'preciso de assistência tecnica' },
  { intent: 'garantia', text: 'quero acionar a garantia' },
  { intent: 'garantia', text: 'quero trocar devolver devolução' },
  { intent: 'garantia', text: 'nao ta ligando parou de funcionar' },
  { intent: 'garantia', text: 'quebrou a tela problema bateria' },
  { intent: 'garantia', text: 'o audio ta chiando' },
  { intent: 'garantia', text: 'esquentando muito' },
  { intent: 'garantia', text: 'descarregando rapido' },
  { intent: 'garantia', text: 'como mando pra garantia' },
  { intent: 'garantia', text: 'tem conserto reparo' },
  { intent: 'garantia', text: 'qual o tempo de garantia' },
  { intent: 'garantia', text: 'camera parou de funcionar' },
  { intent: 'garantia', text: 'veio riscado amassado quebrado' },
  { intent: 'garantia', text: 'celular travando muito' },
  { intent: 'garantia', text: 'reiniciando sozinho' },
  { intent: 'garantia', text: 'nao carrega mais' },
  { intent: 'garantia', text: 'tela piscando' },
  { intent: 'garantia', text: 'mancha na tela do celular' },
  { intent: 'garantia', text: 'face id parou' },
  { intent: 'garantia', text: 'biometria nao funciona' },
  { intent: 'garantia', text: 'wifi nao conecta' },
  { intent: 'garantia', text: 'sem sinal de rede' },
  { intent: 'garantia', text: 'nao le o chip' },
  { intent: 'garantia', text: 'bateria viciada' },
  { intent: 'garantia', text: 'quero cancelar a compra' },
  { intent: 'garantia', text: 'direito de arrependimento 7 dias' },
  { intent: 'garantia', text: 'produto diferente do anuncio' },
  { intent: 'garantia', text: 'falsificado nao e original' },
  { intent: 'garantia', text: 'celular pifou' },
  { intent: 'garantia', text: 'ta ruim' },
  { intent: 'garantia', text: 'nao gostei do aparelho' },
  { intent: 'garantia', text: 'como faco pra trocar' },
  { intent: 'garantia', text: 'assistencia cobre isso' },
  { intent: 'garantia', text: 'perdi a nota fiscal' },
  { intent: 'garantia', text: 'vidro traseiro quebrou' },
  { intent: 'garantia', text: 'microfone falhando' },
  { intent: 'garantia', text: 'touch nao responde' },
  { intent: 'garantia', text: 'aparelho apagou do nada' },

  // RASTREAMENTO (40 exemplos)
  { intent: 'rastreamento', text: 'onde está meu pedido' },
  { intent: 'rastreamento', text: 'não chegou ainda entrega atrasada' },
  { intent: 'rastreamento', text: 'código de rastreio correios' },
  { intent: 'rastreamento', text: 'cadê minha entrega' },
  { intent: 'rastreamento', text: 'qual o prazo de entrega' },
  { intent: 'rastreamento', text: 'quando vai chegar' },
  { intent: 'rastreamento', text: 'ta demorando muito' },
  { intent: 'rastreamento', text: 'status do pedido parado' },
  { intent: 'rastreamento', text: 'transportadora nao atualiza' },
  { intent: 'rastreamento', text: 'pacote perdido extraviado' },
  { intent: 'rastreamento', text: 'meu rastreio nao funciona' },
  { intent: 'rastreamento', text: 'como acompanho o envio' },
  { intent: 'rastreamento', text: 'foi postado ja' },
  { intent: 'rastreamento', text: 'saiu pra entrega' },
  { intent: 'rastreamento', text: 'qual e a transportadora' },
  { intent: 'rastreamento', text: 'manda o link de rastreio' },
  { intent: 'rastreamento', text: 'rastrear objeto' },
  { intent: 'rastreamento', text: 'nao to conseguindo rastrear' },
  { intent: 'rastreamento', text: 'onde vejo o status' },
  { intent: 'rastreamento', text: 'tem codigo de rastreamento' },
  { intent: 'rastreamento', text: 'quero saber onde esta' },
  { intent: 'rastreamento', text: 'vai demorar pra chegar' },
  { intent: 'rastreamento', text: 'entrega expressa sedex pac' },
  { intent: 'rastreamento', text: 'prazo era hoje e nao chegou' },
  { intent: 'rastreamento', text: 'entregaram mas nao recebi' },
  { intent: 'rastreamento', text: 'consta como entregue mas nao chegou' },
  { intent: 'rastreamento', text: 'atualiza o rastreio' },
  { intent: 'rastreamento', text: 'caminho do meu pedido' },
  { intent: 'rastreamento', text: 'rastrear compra' },
  { intent: 'rastreamento', text: 'codigo invalido' },
  { intent: 'rastreamento', text: 'nao sei rastrear' },
  { intent: 'rastreamento', text: 'quero o numero de rastreio' },
  { intent: 'rastreamento', text: 'enviaram meu pedido' },
  { intent: 'rastreamento', text: 'quando postam' },
  { intent: 'rastreamento', text: 'quando vcs enviam' },
  { intent: 'rastreamento', text: 'qual a previsao' },
  { intent: 'rastreamento', text: 'data de entrega' },
  { intent: 'rastreamento', text: 'prazo estourou' },
  { intent: 'rastreamento', text: 'ta em qual cidade' },
  { intent: 'rastreamento', text: 'como rastrear' },

  // SUPORTE (40 exemplos)
  { intent: 'suporte', text: 'quero falar com um atendente humano' },
  { intent: 'suporte', text: 'preciso de ajuda humana atendente real' },
  { intent: 'suporte', text: 'abrir um ticket reclamacao' },
  { intent: 'suporte', text: 'estou com um problema ajuda suporte' },
  { intent: 'suporte', text: 'nao consigo resolver' },
  { intent: 'suporte', text: 'me passa pra uma pessoa' },
  { intent: 'suporte', text: 'chama alguem ai' },
  { intent: 'suporte', text: 'quero reclamar ouvidoria' },
  { intent: 'suporte', text: 'robo burro me passa pra atendente' },
  { intent: 'suporte', text: 'como abro um chamado' },
  { intent: 'suporte', text: 'preciso falar com o suporte tecnico' },
  { intent: 'suporte', text: 'tenho uma duvida especifica' },
  { intent: 'suporte', text: 'quero tirar uma duvida com alguem' },
  { intent: 'suporte', text: 'ninguem me responde' },
  { intent: 'suporte', text: 'alguem me ajuda' },
  { intent: 'suporte', text: 'atendimento horrivel' },
  { intent: 'suporte', text: 'falar com especialista' },
  { intent: 'suporte', text: 'nao encontrei minha resposta' },
  { intent: 'suporte', text: 'como faco pra ter ajuda' },
  { intent: 'suporte', text: 'suporte whatsapp' },
  { intent: 'suporte', text: 'me passa o numero do zap de vcs' },
  { intent: 'suporte', text: 'contato de vcs' },
  { intent: 'suporte', text: 'qual o telefone da loja' },
  { intent: 'suporte', text: 'quero resolver meu problema com uma pessoa' },
  { intent: 'suporte', text: 'falar com gente' },
  { intent: 'suporte', text: 'quero falar com a loja' },
  { intent: 'suporte', text: 'transferir para um humano' },
  { intent: 'suporte', text: 'acionar o suporte' },
  { intent: 'suporte', text: 'preciso de suporte' },
  { intent: 'suporte', text: 'onde abro um ticket' },
  { intent: 'suporte', text: 'ajuda por favor' },
  { intent: 'suporte', text: 'vcs tem telefone' },
  { intent: 'suporte', text: 'nao quero falar com robo' },
  { intent: 'suporte', text: 'chat com atendente' },
  { intent: 'suporte', text: 'como reclamo' },
  { intent: 'suporte', text: 'alguem ai' },
  { intent: 'suporte', text: 'to com duvida' },
  { intent: 'suporte', text: 'fazer reclamacao' },
  { intent: 'suporte', text: 'quero deixar uma reclamacao' },
  { intent: 'suporte', text: 'procon' },

  // SAUDACAO (40 exemplos)
  { intent: 'saudacao', text: 'oi ola bom dia boa tarde boa noite' },
  { intent: 'saudacao', text: 'tudo bem como vai e ai' },
  { intent: 'saudacao', text: 'opa bao' },
  { intent: 'saudacao', text: 'fala ai beleza' },
  { intent: 'saudacao', text: 'eae suave' },
  { intent: 'saudacao', text: 'koe qual foi' },
  { intent: 'saudacao', text: 'saudacoes' },
  { intent: 'saudacao', text: 'tem alguem ai oi' },
  { intent: 'saudacao', text: 'ola chatbot' },
  { intent: 'saudacao', text: 'bom dia tudo bem com voce' },
  { intent: 'saudacao', text: 'boa tarde robozinho' },
  { intent: 'saudacao', text: 'boa noite pessoal' },
  { intent: 'saudacao', text: 'hi hello' },
  { intent: 'saudacao', text: 'bom dia loja' },
  { intent: 'saudacao', text: 'ei oie' },
  { intent: 'saudacao', text: 'eita e ai' },
  { intent: 'saudacao', text: 'ola boa tarde' },
  { intent: 'saudacao', text: 'oi boa noite' },
  { intent: 'saudacao', text: 'tudo joia' },
  { intent: 'saudacao', text: 'alou oi' },
  { intent: 'saudacao', text: 'oioi' },
  { intent: 'saudacao', text: 'como vcs estao' },
  { intent: 'saudacao', text: 'ola pessoal' },
  { intent: 'saudacao', text: 'olha eu aqui' },
  { intent: 'saudacao', text: 'cheguei oi' },
  { intent: 'saudacao', text: 'opa amigo' },
  { intent: 'saudacao', text: 'fala meu chegado' },
  { intent: 'saudacao', text: 'e ai glr' },
  { intent: 'saudacao', text: 'oi vcs estao' },
  { intent: 'saudacao', text: 'salve' },
  { intent: 'saudacao', text: 'ola vanta' },
  { intent: 'saudacao', text: 'vantatech oi' },
  { intent: 'saudacao', text: 'dia' },
  { intent: 'saudacao', text: 'tarde' },
  { intent: 'saudacao', text: 'noite' },
  { intent: 'saudacao', text: 'alo' },
  { intent: 'saudacao', text: 'bomdia' },
  { intent: 'saudacao', text: 'boatarde' },
  { intent: 'saudacao', text: 'boanoite' },
  { intent: 'saudacao', text: 'olaaa' },

  // DESPEDIDA (40 exemplos)
  { intent: 'despedida', text: 'tchau valeu obrigado ate logo' },
  { intent: 'despedida', text: 'so isso mesmo tchau' },
  { intent: 'despedida', text: 'flw' },
  { intent: 'despedida', text: 'fui partiu' },
  { intent: 'despedida', text: 'obrigado pela ajuda' },
  { intent: 'despedida', text: 'valeu demais' },
  { intent: 'despedida', text: 'ate mais' },
  { intent: 'despedida', text: 'obrigadao vlw' },
  { intent: 'despedida', text: 'agradeco muito tchau' },
  { intent: 'despedida', text: 'boa noite tchau' },
  { intent: 'despedida', text: 'bom dia tchau' },
  { intent: 'despedida', text: 'boa tarde tchau' },
  { intent: 'despedida', text: 'adeus' },
  { intent: 'despedida', text: 'ja entendi obrigado' },
  { intent: 'despedida', text: 'tudo certo obg' },
  { intent: 'despedida', text: 'duvida resolvida valeu' },
  { intent: 'despedida', text: 'show de bola tchau' },
  { intent: 'despedida', text: 'perfeito obrigado' },
  { intent: 'despedida', text: 'muito grato' },
  { intent: 'despedida', text: 'obrigada' },
  { intent: 'despedida', text: 'brigado' },
  { intent: 'despedida', text: 'brigadao' },
  { intent: 'despedida', text: 'abracos' },
  { intent: 'despedida', text: 'ate a proxima' },
  { intent: 'despedida', text: 'so isso obrigado' },
  { intent: 'despedida', text: 'por enquanto so vlw' },
  { intent: 'despedida', text: 'vou indo tchau' },
  { intent: 'despedida', text: 'deu certo vlw' },
  { intent: 'despedida', text: 'valeu ai' },
  { intent: 'despedida', text: 'tmj vlw' },
  { intent: 'despedida', text: 'tamo junto irmao' },
  { intent: 'despedida', text: 'era so isso mesmo' },
  { intent: 'despedida', text: 'pode fechar obg' },
  { intent: 'despedida', text: 'valeu meu bom' },
  { intent: 'despedida', text: 'ok obrigado' },
  { intent: 'despedida', text: 'blz vlw' },
  { intent: 'despedida', text: 'bye' },
  { intent: 'despedida', text: 'tchauzinho' },
  { intent: 'despedida', text: 'obgd' },
  { intent: 'despedida', text: 'bom trabalho tchau' }
];

export function classifyIntent(normalizedText: string): Intent {
  const fuse = new Fuse(INTENT_EXAMPLES, {
    keys: ['text'],
    includeScore: true,
    threshold: 0.8, // Permite busca aproximada mais tolerante
    ignoreLocation: true // Busca palavras em qualquer lugar da frase
  });

  const results = fuse.search(normalizedText);

  if (results.length > 0 && results[0].score !== undefined && results[0].score < 0.75) {
    return results[0].item.intent as Intent;
  }

  // Fallback baseado em palavras-chave fortes caso o Fuse falhe
  if (normalizedText.includes('problema') || normalizedText.includes('nao liga') || normalizedText.includes('defeito') || normalizedText.includes('quebro')) {
    return 'garantia';
  }
  if (normalizedText.includes('comprar') || normalizedText.includes('valor') || normalizedText.includes('preco')) {
    return 'comprar';
  }
  if (normalizedText.includes('rastrei') || normalizedText.includes('cade') || normalizedText.includes('entrega')) {
    return 'rastreamento';
  }

  return 'desconhecido';
}
